version: '3.8'
services:
  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    profiles: ['reverse-proxy']
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  db:
    image: postgres:14.2
    stop_signal: SIGINT
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  manager:
    image: konyha/manager:latest
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${MANAGER_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=web"
  sitegen:
    image: konyha/sitegen:latest
    stdin_open: true
    depends_on:
      - db
      - manager
    ports:
      - "7777:7777"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${SITEGEN_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=web"
volumes:
  db:
    driver: local
